Blog databricks
smart-data-lake/smart-data-lake pull request #499
Opened 2022-04-06 05:31 UTC by mand35

This Blog entry describes how to provision SDL on Databricks with a two stage download, select ingest pipeline into the Databricks database.
Another try

2022-04-06 10:20 UTC, zzeekk reviewed
Nice Post and good level of detail for a post.

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +Many analytics applications are ported to the cloud, Data Lakes and Datahouses in the cloud becoming more and more popular. The [Databricks](https://databricks.com) platform provides an easy accessib
```suggestion
Many analytics applications are ported to the cloud, Data Lakes and Lakehouses in the cloud becoming more and more popular. The [Databricks](https://databricks.com) platform provides an easy accessible and easy configurable. SmartDataLake Builder on the other hand provides an open source, portable automation tool to load and transform the data.
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +Before jumping in, it should be mentioned, that there are also other methods to deploy SDLB in the cloud, e.g. using containers on Azure.
```suggestion
Before jumping in, it should be mentioned, that there are also many other methods to deploy SDLB in the cloud, e.g. using containers on Azure, Azure Kubernetes Service, Azure Synapse Clusters, ...
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +	  This need to match with the version we build SDLB later. Here `10.4 TLS` is selected with `Spark 3.2.1` and `Scala 2.12`.
```suggestion
	  This need to match with the Spark version we build SDLB later. Here `10.4 TLS` is selected with `Spark 3.2.1` and `Scala 2.12`. 
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +	  Alternatively, SDL could be build with a different version.
```suggestion
	  Alternatively, SDLB can be build with a different Spark versions, see also [Architecture](../../docs/architecture) for supported versions. 
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +	  Thus, we provide a newer typesafe version in an initialization script: *Advanced options* -> *Init Scripts* specify `dbfs:/databricks/scripts/config-install.sh`
```suggestion
	- typesafe library version correction script: the workspace currently includes version 1.2.1 from com.typesafe:config java library. 
	  SDLB relies on functions of a newer version (>1.3.0) of this library. 
	  Thus, we provide a newer version of the com.typesafe:config java library in an initialization script: *Advanced options* -> *Init Scripts* specify `dbfs:/databricks/scripts/config-install.sh`
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +		Note: to double check the typesafe version I ran `grep typesafe pom.xml` in the [SmartDataLake](https://github.com/smart-data-lake/smart-data-lake.git) source
```suggestion
		Note: to double check the library version I ran `grep typesafe pom.xml` in the [SmartDataLake](https://github.com/smart-data-lake/smart-data-lake.git) source
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +       We need to provide the SDL sources and all required libraries. Therefore, we compile and pack the Scala code into a Jar including the dependencies. We use the [getting-started](https://github.
```suggestion
       We need to provide the SDLB sources and all required libraries. Therefore, we compile and pack the Scala code into a Jar including the dependencies. We use the [getting-started](https://github.com/smart-data-lake/getting-started.git) as dummy project, which itself pulls the SDLB sources. 
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +	General build instructions can be fond in the [getting-started](../../docs/getting-started/setup#compile-scala-classes) documentation.
```suggestion
	General build instructions can be found in the [getting-started](../../docs/getting-started/setup#compile-scala-classes) documentation. 
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +	- **SDLB application**: As an example a dataset from Airbnb NYC will be downloaded from Github, first written into a CSV file and later partially ported into a database. Therefore, the pipeline is d
```suggestion
	- **SDLB application**: As an example a dataset from Airbnb NYC will be downloaded from Github, first written into a CSV file and later partially ported into a table. Therefore, the pipeline is defined first locally in a new file `application.conf`:
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +	After running the SDLB pipeline the data should be downloaded into the staging file and selected parts into the database:
```suggestion
	After running the SDLB pipeline the data should be downloaded into the staging file and selected parts into the table `stg_ab:`
```

2022-04-06 10:20 UTC, zzeekk commented on blog/2022-04-07-SDL_databricks/2022-04-07-Databricks.md
> +There are a few steps necessary, including building and uploading SDB. Further, we need to be careful with the used versions of the underlying libraries. With these few steps we can reveal the power
```suggestion
There are a few steps necessary, including building and uploading SDLB. Further, we need to be careful with the used versions of the underlying libraries. With these few steps we can reveal the power of SDLB and Databricks, creating a portable and reproducible pipeline into a Databricks Lakehouse.  
```

2022-04-07 06:09 UTC, mand35 commented
Many thanks @zzeekk for the corrections.

2022-04-07 06:57 UTC, zzeekk approved these changes
Great, thanks!

2022-04-08 06:57 UTC, pgruetter requested changes
I've created a pull request with some proposals. 

General:
- As discussed, I think we should remove the need for 2 jobs in this example as it gives a wrong impression
- Probably from the examples, but why is the table called `stg_ab` for a DataObject `int_ab` ?

2022-04-08 13:20 UTC, mand35 commented
Thanks both. I merged @pgruetter suggestions, removed the second job step and cleaned it.

2022-04-08 13:33 UTC, merged